name: CI/CD with GitOps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t 17riya/myapp:${{ github.sha }} .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" |
           docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push 17riya/myapp:${{ github.sha }}

    - name: Update Kubernetes deployment
      run: |
        sed -i "s|image: .*|image: 17riya/myapp:${{ github.sha }}|" k8s/deployment.yaml
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add k8s/deployment.yaml
        git commit -m "Update image tag"
        git push
